// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGpus(t *testing.T) {
	t.Parallel()

	query := Gpus()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGpusDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGpusQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Gpus().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGpusSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GpuSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGpusExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GpuExists(ctx, tx, o.GPUID)
	if err != nil {
		t.Errorf("Unable to check if Gpu exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GpuExists to return true, but got false.")
	}
}

func testGpusFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	gpuFound, err := FindGpu(ctx, tx, o.GPUID)
	if err != nil {
		t.Error(err)
	}

	if gpuFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGpusBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Gpus().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGpusOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Gpus().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGpusAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	gpuOne := &Gpu{}
	gpuTwo := &Gpu{}
	if err = randomize.Struct(seed, gpuOne, gpuDBTypes, false, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}
	if err = randomize.Struct(seed, gpuTwo, gpuDBTypes, false, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gpuOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gpuTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Gpus().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGpusCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	gpuOne := &Gpu{}
	gpuTwo := &Gpu{}
	if err = randomize.Struct(seed, gpuOne, gpuDBTypes, false, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}
	if err = randomize.Struct(seed, gpuTwo, gpuDBTypes, false, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gpuOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gpuTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func gpuBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func gpuAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Gpu) error {
	*o = Gpu{}
	return nil
}

func testGpusHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Gpu{}
	o := &Gpu{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, gpuDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Gpu object: %s", err)
	}

	AddGpuHook(boil.BeforeInsertHook, gpuBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	gpuBeforeInsertHooks = []GpuHook{}

	AddGpuHook(boil.AfterInsertHook, gpuAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	gpuAfterInsertHooks = []GpuHook{}

	AddGpuHook(boil.AfterSelectHook, gpuAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	gpuAfterSelectHooks = []GpuHook{}

	AddGpuHook(boil.BeforeUpdateHook, gpuBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	gpuBeforeUpdateHooks = []GpuHook{}

	AddGpuHook(boil.AfterUpdateHook, gpuAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	gpuAfterUpdateHooks = []GpuHook{}

	AddGpuHook(boil.BeforeDeleteHook, gpuBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	gpuBeforeDeleteHooks = []GpuHook{}

	AddGpuHook(boil.AfterDeleteHook, gpuAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	gpuAfterDeleteHooks = []GpuHook{}

	AddGpuHook(boil.BeforeUpsertHook, gpuBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	gpuBeforeUpsertHooks = []GpuHook{}

	AddGpuHook(boil.AfterUpsertHook, gpuAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	gpuAfterUpsertHooks = []GpuHook{}
}

func testGpusInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGpusInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(gpuColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGpuToManyGpuThings(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Gpu
	var b, c GpuThing

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, gpuThingDBTypes, false, gpuThingColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, gpuThingDBTypes, false, gpuThingColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.GpuID, a.GPUID)
	queries.Assign(&c.GpuID, a.GPUID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.GpuThings().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.GpuID, b.GpuID) {
			bFound = true
		}
		if queries.Equal(v.GpuID, c.GpuID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GpuSlice{&a}
	if err = a.L.LoadGpuThings(ctx, tx, false, (*[]*Gpu)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.GpuThings); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.GpuThings = nil
	if err = a.L.LoadGpuThings(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.GpuThings); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGpuToManyAddOpGpuThings(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Gpu
	var b, c, d, e GpuThing

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gpuDBTypes, false, strmangle.SetComplement(gpuPrimaryKeyColumns, gpuColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*GpuThing{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, gpuThingDBTypes, false, strmangle.SetComplement(gpuThingPrimaryKeyColumns, gpuThingColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*GpuThing{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddGpuThings(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.GPUID, first.GpuID) {
			t.Error("foreign key was wrong value", a.GPUID, first.GpuID)
		}
		if !queries.Equal(a.GPUID, second.GpuID) {
			t.Error("foreign key was wrong value", a.GPUID, second.GpuID)
		}

		if first.R.Gpu != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Gpu != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.GpuThings[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.GpuThings[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.GpuThings().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testGpuToManySetOpGpuThings(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Gpu
	var b, c, d, e GpuThing

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gpuDBTypes, false, strmangle.SetComplement(gpuPrimaryKeyColumns, gpuColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*GpuThing{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, gpuThingDBTypes, false, strmangle.SetComplement(gpuThingPrimaryKeyColumns, gpuThingColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetGpuThings(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.GpuThings().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetGpuThings(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.GpuThings().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GpuID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GpuID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.GPUID, d.GpuID) {
		t.Error("foreign key was wrong value", a.GPUID, d.GpuID)
	}
	if !queries.Equal(a.GPUID, e.GpuID) {
		t.Error("foreign key was wrong value", a.GPUID, e.GpuID)
	}

	if b.R.Gpu != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Gpu != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Gpu != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Gpu != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.GpuThings[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.GpuThings[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testGpuToManyRemoveOpGpuThings(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Gpu
	var b, c, d, e GpuThing

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gpuDBTypes, false, strmangle.SetComplement(gpuPrimaryKeyColumns, gpuColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*GpuThing{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, gpuThingDBTypes, false, strmangle.SetComplement(gpuThingPrimaryKeyColumns, gpuThingColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddGpuThings(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.GpuThings().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveGpuThings(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.GpuThings().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GpuID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GpuID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Gpu != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Gpu != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Gpu != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Gpu != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.GpuThings) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.GpuThings[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.GpuThings[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testGpusReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGpusReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GpuSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGpusSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Gpus().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	gpuDBTypes = map[string]string{`GPUID`: `integer`}
	_          = bytes.MinRead
)

func testGpusUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(gpuPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(gpuAllColumns) == len(gpuPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGpusSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(gpuAllColumns) == len(gpuPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Gpu{}
	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gpuDBTypes, true, gpuPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(gpuAllColumns, gpuPrimaryKeyColumns) {
		fields = gpuAllColumns
	} else {
		fields = strmangle.SetComplement(
			gpuAllColumns,
			gpuPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GpuSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGpusUpsert(t *testing.T) {
	t.Parallel()

	if len(gpuAllColumns) == len(gpuPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Gpu{}
	if err = randomize.Struct(seed, &o, gpuDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Gpu: %s", err)
	}

	count, err := Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, gpuDBTypes, false, gpuPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Gpu struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Gpu: %s", err)
	}

	count, err = Gpus().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
